const $=id=>document.getElementById(id);let HISTORY=[];let TICKETS=[];let LAST_REPORT=null;
const PRIMES=new Set([2,3,5,7,11,13,17,19,23]);const FIB=new Set([1,2,3,5,8,13,21]);const FRAME=new Set([1,2,3,4,5,6,10,11,15,16,20,21,22,23,24,25]);const PRIOR=new Set([1,2,3,7,10,11,12,19,23,25]);const UNIVERSE=3268760;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function mask(a){let m=0;for(const n of a)m|=1<<(n-1);return m}function bits(m){const a=[];for(let i=0;i<25;i++)if(m&(1<<i))a.push(i+1);return a}function overlap(a,b){let c=0;const s=new Set(a);for(const n of b)c+=s.has(n);return c}
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}}function choice(a,r){return a[Math.floor(r()*a.length)]}
function shuffle(a,r){for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function freq(history,w){const c=Array(26).fill(0),start=Math.max(0,history.length-w);for(let i=start;i<history.length;i++)for(const n of history[i].dezenas)c[n]++;return c}
function stats(history,w){const total=freq(history,history.length),recent=freq(history,Math.min(w,history.length)),r20=freq(history,Math.min(20,history.length));const delay=Array(26).fill(history.length);for(let n=1;n<=25;n++)for(let i=history.length-1;i>=0;i--){if(history[i].dezenas.includes(n)){delay[n]=history.length-1-i;break}}return {total,recent,r20,delay}}
function numScore(n,s,h){const N=h.length||1,W=Math.min(500,N),a=s.total[n]/(N*15/25),b=s.recent[n]/(Math.min(W,N)*15/25),c=s.r20[n]/(Math.min(20,N)*15/25),d=Math.min(s.delay[n],30)/30;return .42*a+.36*b+.12*c+.05*d+.05*(PRIOR.has(n)?1:0)}
function structure(t){let ev=0,pr=0,fi=0,fr=0,sum=0;const rows=[0,0,0,0,0],cols=[0,0,0,0,0];for(const n of t){sum+=n;ev+=n%2===0;pr+=PRIMES.has(n);fi+=FIB.has(n);fr+=FRAME.has(n);rows[Math.floor((n-1)/5)]++;cols[(n-1)%5]++}let z=0;z+=18*(1-Math.min(1,Math.abs(ev-7.5)/7.5));z+=10*(1-Math.min(1,Math.abs(pr-5)/5));z+=8*(1-Math.min(1,Math.abs(fi-4)/5));z+=6*(1-Math.min(1,Math.abs(fr-9)/9));z+=18*(1-Math.min(1,Math.abs(sum-195)/75));z+=10*(1-Math.min(1,rows.reduce((q,x)=>q+Math.max(0,x-4),0)/8));z+=10*(1-Math.min(1,cols.reduce((q,x)=>q+Math.max(0,x-4),0)/8));return z}
function scoreTicket(t,s,h){return t.reduce((q,n)=>q+numScore(n,s,h),0)*1000+structure(t)}
function weightedTicket(s,h,r){const chosen=[],avail=Array.from({length:25},(_,i)=>i+1);for(let k=0;k<15;k++){const ws=avail.map(n=>Math.max(1e-5,numScore(n,s,h))**.58),sum=ws.reduce((a,b)=>a+b,0);let x=r()*sum,idx=0;for(;idx<ws.length-1;idx++){x-=ws[idx];if(x<=0)break}chosen.push(avail[idx]);avail.splice(idx,1)}return chosen.sort((a,b)=>a-b)}
function cover(t){const out=new Set([mask(t)]), S=new Set(t), O=Array.from({length:25},(_,i)=>i+1).filter(n=>!S.has(n));for(const a of S)for(const b of O){const u=t.filter(n=>n!==a).concat(b).sort((x,y)=>x-y);out.add(mask(u))}return out}
function hit(t,d){const S=new Set(d),c=t.reduce((q,n)=>q+(S.has(n)?1:0),0);return c}
function candidatePool(h,n,strategy,seed,w){const r=rng(seed),s=stats(h,w),pool=new Map(),attempts=Math.max(400,n*45);for(let i=0;i<attempts;i++){let t;if(strategy==='coverage'||strategy==='max'){const d=choice(h,r).dezenas.slice();const outside=Array.from({length:25},(_,j)=>j+1).filter(x=>!d.includes(x));if(r()<.78){d[Math.floor(r()*15)]=choice(outside,r);t=d.sort((a,b)=>a-b)}else t=weightedTicket(s,h,r)}else t=weightedTicket(s,h,r);pool.set(t.join('-'),t)}return [...pool.values()].sort((a,b)=>scoreTicket(b,s,h)-scoreTicket(a,s,h))}
function greedy(pool,k,h,seed){const r=rng(seed), selected=[],covered=new Set(), hist=h.slice(-Math.min(500,h.length));const cov=new Map();const candidates=pool.slice(0,Math.min(pool.length,3500));for(let i=0;i<k;i++){let best=null,bestVal=-1e99;const sample=i<4?candidates:candidates.slice(0,Math.min(candidates.length,1000));for(const t of sample){if(selected.some(x=>x.join('-')===t.join('-')))continue;const key=t.join('-');if(!cov.has(key))cov.set(key,cover(t));const C=cov.get(key);let nu=0;for(const x of C)if(!covered.has(x))nu++;let hn=0;for(const d of hist){const m=mask(d.dezenas);if(!covered.has(m)&&C.has(m))hn++}let pen=0;for(const x of selected)pen+=Math.max(0,overlap(t,x)-9)**2;const val=nu+25*hn-2*pen+r()*.01;if(val>bestVal){bestVal=val;best=t}}if(!best)break;selected.push(best);for(const x of cov.get(best.join('-')))covered.add(x)}return selected}
function objective(tickets,h,w){const recent=h.slice(-Math.min(100,h.length));let hist14=0,recent14=0,bestSum=0;for(const d of h){let mx=0;for(const t of tickets)mx=Math.max(mx,hit(t,d.dezenas));if(mx>=14)hist14++;bestSum+=mx}for(const d of recent){let mx=0;for(const t of tickets)mx=Math.max(mx,hit(t,d.dezenas));if(mx>=14)recent14++}let uni=new Set();for(const t of tickets)for(const x of cover(t))uni.add(x);let pen=0;for(let i=0;i<tickets.length;i++)for(let j=i+1;j<tickets.length;j++)pen+=Math.max(0,overlap(tickets[i],tickets[j])-10)**2;return hist14*1000+recent14*250+uni.size*.03+(bestSum/Math.max(1,h.length))*20-pen*1.5}
function mutate(t,r){const s=new Set(t),a=choice([...s],r),o=Array.from({length:25},(_,i)=>i+1).filter(n=>!s.has(n));s.delete(a);s.add(choice(o,r));return [...s].sort((a,b)=>a-b)}
function optimize(tickets,h,steps,seed,quantum){let r=rng(seed),cur=tickets.map(x=>x.slice()),cv=objective(cur,h);let best=cur.map(x=>x.slice()),bv=cv;for(let i=0;i<steps;i++){const c=cur.map(x=>x.slice()),j=Math.floor(r()*c.length);c[j]=mutate(c[j],r);if(new Set(c.map(x=>x.join('-'))).size<c.length)continue;let nv=objective(c,h),temp=8*(1-i/steps)+.05;if(quantum&&r()<.06)temp*=6;if(nv>cv||r()<Math.exp(Math.max(-40,(nv-cv)/temp))){cur=c;cv=nv;if(nv>bv){best=c.map(x=>x.slice());bv=nv}}}return best}
function generate(h,k,strategy,it,w){const seed=Date.now()>>>0;const pool=candidatePool(h,Math.max(1000,k*60),strategy,seed,w);let t=greedy(pool,k,h,seed+11);if(strategy==='max')t=optimize(t,h,it,seed+77,true);else if(strategy==='hybrid')t=optimize(t,h,Math.min(it,900),seed+77,false);return t}
function metrics(tickets,h){let coveredHist=0,best=0,dist={};for(const d of h){let mx=0;for(const t of tickets)mx=Math.max(mx,hit(t,d.dezenas));dist[mx]=(dist[mx]||0)+1;best+=mx;if(mx>=14)coveredHist++}const U=new Set();for(const t of tickets)for(const x of cover(t))U.add(x);return {histPct:100*coveredHist/Math.max(1,h.length),uniPct:100*U.size/UNIVERSE,uniCount:U.size,bestAvg:best/Math.max(1,h.length),dist}};
function renderGames(){if(!TICKETS.length){$('gamesList').innerHTML='<div class="empty">Gere os jogos para começar.</div>';return}$('gamesList').innerHTML=TICKETS.map((t,i)=>`<div class="game"><div class="n">Jogo ${i+1}</div><div class="nums">${t.map(n=>`<span class="ball">${String(n).padStart(2,'0')}</span>`).join('')}</div></div>`).join('')}
function renderMetrics(){const m=metrics(TICKETS,HISTORY);$('mDraws').textContent=HISTORY.length.toLocaleString('pt-BR');$('mLast').textContent=HISTORY.at(-1)?.concurso??'—';$('mHist').textContent=TICKETS.length?m.histPct.toFixed(2)+'%':'—';$('mUni').textContent=TICKETS.length?m.uniPct.toFixed(3)+'%':'—';$('coverageBox').innerHTML=TICKETS.length?`<h3>📐 Cobertura real</h3><p><b>${m.histPct.toFixed(2)}%</b> dos concursos históricos tiveram pelo menos uma aposta com 14+.</p><p><b>${m.uniCount.toLocaleString('pt-BR')}</b> combinações distintas do universo de 3.268.760 estão cobertas por 14+/15 (${m.uniPct.toFixed(3)}%).</p><p>Média do melhor jogo por concurso: <b>${m.bestAvg.toFixed(3)}</b>.</p><p class="muted">A cobertura universal é um cálculo exato para os jogos gerados; ela não significa previsão do próximo sorteio.</p>`:'<p class="muted">Gere jogos para calcular.</p>';}
function renderStats(){const s=stats(HISTORY,500);const arr=Array.from({length:25},(_,i)=>i+1).map(n=>({n,total:s.total[n],recent:s.recent[n],delay:s.delay[n]})).sort((a,b)=>b.recent-a.recent);$('statsBox').innerHTML='<h3>📊 Números</h3><table><tr><th>Nº</th><th>Hist.</th><th>Janela</th><th>Atraso</th></tr>'+arr.map(x=>`<tr><td>${String(x.n).padStart(2,'0')}</td><td>${x.total}</td><td>${x.recent}</td><td>${x.delay}</td></tr>`).join('')+'</table>'}
async function runBacktest(){const games=+$('games').value,targets=Math.min(30,Math.max(5,Math.floor(600/games))),strategy=$('strategy').value,it=+$('iterations').value;let out=[];for(let j=HISTORY.length-targets;j<HISTORY.length;j++){const train=HISTORY.slice(0,j),t=generate(train,games,strategy==='max'?'max':strategy,Math.min(it,500),500);let mx=0;for(const x of t)mx=Math.max(mx,hit(x,HISTORY[j].dezenas));out.push({c:HISTORY[j].concurso,h:mx});await sleep(0)}const c={};for(const x of out)c[x.h]=(c[x.h]||0)+1;$('btBox').innerHTML='<h3>🧪 Walk-forward</h3><p>Janela: últimos '+targets+' concursos. Cada concurso é testado sem usar o próprio resultado no treinamento.</p><table><tr><th>Faixa</th><th>Quantidade</th></tr>'+Object.keys(c).sort((a,b)=>b-a).map(k=>`<tr><td>${k} acertos</td><td>${c[k]}</td></tr>`).join('')+'</table><p class="muted">Isso é backtest, não garantia futura.</p>';}
async function load(){try{const r=await fetch('data/history.json',{cache:'no-store'});HISTORY=await r.json();$('status').textContent=`● online · ${HISTORY.length} concursos`;renderStats();renderMetrics()}catch(e){$('status').textContent='⚠ dados locais indisponíveis'}}
async function refresh(){const b=$('refresh');b.disabled=true;b.textContent='⏳ Sincronizando…';try{const r=await fetch('data/history.json?ts='+Date.now(),{cache:'no-store'});HISTORY=await r.json();$('status').textContent=`● dados atualizados · ${HISTORY.length} concursos`;renderStats();renderMetrics()}finally{b.disabled=false;b.textContent='🌐 ATUALIZAR DADOS'}}
$('generate').onclick=async()=>{const b=$('generate');b.disabled=true;b.textContent='⏳ Otimizando…';await sleep(20);TICKETS=generate(HISTORY,+$('games').value,$('strategy').value,+$('iterations').value,+$('window').value);renderGames();renderMetrics();b.disabled=false;b.textContent='🚀 GERAR JOGOS';document.querySelector('[data-tab="gamesTab"]').click()};
$('optimize').onclick=async()=>{if(!TICKETS.length){$('generate').click();return}const b=$('optimize');b.disabled=true;b.textContent='🧠 Buscando…';await sleep(20);TICKETS=optimize(TICKETS,HISTORY,+$('iterations').value,Date.now()>>>0,true);renderGames();renderMetrics();b.disabled=false;b.textContent='🧠 OTIMIZAR'};
$('backtest').onclick=()=>runBacktest();$('refresh').onclick=refresh;
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('install').hidden=false});$('install').onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$('install').hidden=true}};if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');load();
